=== JoTesla/sleeparchiver/src/com/pavelfatin/sleeparchiver/model/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://pavelfatin.com/sleeparchiver"
           targetNamespace="http://pavelfatin.com/sleeparchiver"
           elementFormDefault="qualified">

    <xs:simpleType name="date">
        <xs:restriction base="xs:date">
            <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="time">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}:\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="window">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="90"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ease">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hard"/>
            <xs:enumeration value="normal"/>
            <xs:enumeration value="easy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="quality">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bad"/>
            <xs:enumeration value="average"/>
            <xs:enumeration value="good"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="document">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="night" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="version" type="xs:float" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="night">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="moments" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="conditions" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="date" type="date" use="optional"/>
            <xs:attribute name="alarm" type="time" use="optional"/>
            <xs:attribute name="window" type="window" use="optional"/>
            <xs:attribute name="toBed" type="time" use="optional"/>
            <xs:attribute name="easeOfFallingAsleep" type="ease" use="optional"/>
            <xs:attribute name="qualityOfSleep" type="quality" use="optional"/>
            <xs:attribute name="easeOfWakingUp" type="ease" use="optional"/>
            <xs:attribute name="alarmWorked" type="xs:boolean" use="optional"/>
            <xs:attribute name="comments" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="moments">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="moment" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="conditions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="condition" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="moment" type="time"/>

    <xs:element name="condition" type="xs:string"/>

</xs:schema>

=== JoTesla/sleeparchiver/src/test/resources/com/pavelfatin/sleeparchiver/model/document/document.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<document xmlns="http://pavelfatin.com/sleeparchiver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://pavelfatin.com/sleeparchiver http://pavelfatin.com/files/sleeparchiver/document.xsd">
    <night date="2005-02-04" alarm="08:45" window="30" toBed="22:15" easeOfFallingAsleep="hard" qualityOfSleep="good" easeOfWakingUp="normal" alarmWorked="true" comments="Foo comment">
        <moments>
            <moment>23:30</moment>
            <moment>03:00</moment>
            <moment>08:30</moment>
        </moments>
        <conditions>
            <condition>Condition A</condition>
            <condition>Condition B</condition>
        </conditions>
    </night>
    <night date="2006-03-05" alarm="09:55" window="20" toBed="23:15" easeOfWakingUp="hard">
        <moments>
            <moment>23:40</moment>
            <moment>05:00</moment>
            <moment>09:10</moment>
        </moments>
        <conditions>
            <condition>Condition D</condition>
            <condition>Condition B</condition>
            <condition>Condition E</condition>
        </conditions>
    </night>
</document>

=== JoTesla/sleeparchiver/test/com/pavelfatin/sleeparchiver/model/document/document.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<document xmlns="http://pavelfatin.com/sleeparchiver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://pavelfatin.com/sleeparchiver http://pavelfatin.com/files/sleeparchiver/document.xsd">
    <night comments="Foo comment" alarmWorked="true" easeOfWakingUp="normal" qualityOfSleep="good" easeOfFallingAsleep="hard" toBed="22:15" window="30" alarm="08:45" date="2005-02-04">
        <moments>
            <moment>23:30</moment>
            <moment>03:00</moment>
            <moment>08:30</moment>
        </moments>
        <conditions>
            <condition>Condition A</condition>
            <condition>Condition B</condition>
        </conditions>
    </night>
    <night easeOfWakingUp="hard" toBed="23:15" window="20" alarm="09:55" date="2006-03-05">
        <moments>
            <moment>23:40</moment>
            <moment>05:00</moment>
            <moment>09:10</moment>
        </moments>
        <conditions>
            <condition>Condition D</condition>
            <condition>Condition B</condition>
            <condition>Condition E</condition>
        </conditions>
    </night>
</document>
